// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(admin)/about-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/about-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/emergency-qr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emergency-qr">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/emergency-qr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/evacuation-centers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evacuation-centers">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/evacuation-centers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/health/applicants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health/applicants">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/health/applicants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/households-residents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/households-residents">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/households-residents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hub">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/incident-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incident-map">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/incident-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/incident-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incident-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/incident-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/requests/[requestId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/[requestId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/requests/[requestId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/residents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/residents">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/residents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/services/sla/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/sla">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/services/sla/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/terms-privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/terms-privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/theme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/theme">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/theme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transactions">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/waste-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/waste-management">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/waste-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resident">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resident/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/reports/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resident/reports/new">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/reports/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resident/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/requests/[requestId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resident/requests/[requestId]">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/requests/[requestId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/requests/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resident/requests/new">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/requests/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resident/requests">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/residents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/residents">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/residents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/resident/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/resident">> = Specific
  const handler = {} as typeof import("../../../src/app/resident/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
