-- Module 10: Health & Medical Drive
-- Tables:  medical_drives, drive_registrations
-- RPC:     register_for_drive  (atomic slot reservation + weighted priority scoring)
--
-- Drive type prefix map (AGENTS.md §4):
--   vaccination → VAC   maternal_care → MAT   blood_drive → BLD
--   dental      → DEN   optical       → OPT   medicine    → MED
--   emergency_kit→ EMK  screening     → SCR   consultation→ CON
--   minor_surgical→SRG  others        → DRV

-- ============================================================================
-- 1. Enums
-- ============================================================================
create type public.drive_type as enum (
  'vaccination',
  'maternal_care',
  'blood_drive',
  'medicine',
  'dental',
  'optical',
  'emergency_kit',
  'screening',
  'consultation',
  'minor_surgical',
  'others'
);

create type public.drive_registration_status as enum (
  'pending',
  'confirmed',
  'attended',
  'cancelled'
);

-- ============================================================================
-- 2. medical_drives
-- ============================================================================
create table public.medical_drives (
  id              uuid        primary key default gen_random_uuid(),
  barangay_id     uuid        not null references public.barangays(id),
  title           text        not null,
  type            public.drive_type not null,
  drive_date      date        not null,
  time_start      time        not null,
  time_end        time        not null,
  location        text        not null default 'Barangay Health Center',
  eligible_criteria text      not null,
  -- Human-readable label for the stock counter shown on the card, e.g.
  -- "Remaining Stock" (vaccination doses) or "Remaining Slots" (consultation).
  stock_label     text        not null default 'Remaining Slots',
  stock_unit      text        not null default 'slots',   -- "doses" | "slots" | etc.
  stock_total     integer     not null check (stock_total > 0),
  stock_remaining integer     not null check (stock_remaining >= 0 and stock_remaining <= stock_total),
  is_active       boolean     not null default true,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on table public.medical_drives is
  'Barangay-scoped health/medical drive events (Module 10). Multi-dose vaccine drives '
  'use stock_unit=''doses''; walk-in consultation drives use stock_unit=''slots''.';

create index medical_drives_date_idx  on public.medical_drives (drive_date)
  where deleted_at is null;
create index medical_drives_bgy_date_idx on public.medical_drives (barangay_id, drive_date)
  where deleted_at is null and is_active = true;

-- updated_at trigger (reuses the project-wide helper from 0001)
create trigger set_medical_drives_updated_at
  before update on public.medical_drives
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 3. drive_registrations
-- ============================================================================
create table public.drive_registrations (
  id               uuid        primary key default gen_random_uuid(),
  drive_id         uuid        not null references public.medical_drives(id),
  user_id          uuid        not null references auth.users(id),
  -- Applicant number generated by the register_for_drive RPC, e.g. "VAC-20260808-0001"
  applicant_number text        not null,
  -- Eligibility fields fed to the priority-scoring formula (AGENTS.md §3)
  age              integer     not null check (age >= 0 and age <= 130),
  is_pwd           boolean     not null default false,
  comorbidities    text[]      not null default '{}',
  prior_dose_date  date,           -- multi-dose vaccines: previous dose date
  priority_score   numeric     not null default 0,
  status           public.drive_registration_status not null default 'pending',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- One registration per user per drive
  unique (drive_id, user_id)
);

comment on table public.drive_registrations is
  'One row per resident–drive pair. priority_score is computed server-side by '
  'register_for_drive so the client never submits a pre-computed score (AGENTS.md §3).';

create index drive_registrations_user_idx  on public.drive_registrations (user_id);
create index drive_registrations_drive_idx on public.drive_registrations (drive_id);

create trigger set_drive_registrations_updated_at
  before update on public.drive_registrations
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 4. Row-Level Security
-- ============================================================================
alter table public.medical_drives     enable row level security;
alter table public.drive_registrations enable row level security;

-- Active drives are publicly readable (guest mode, same as announcements/doc-types).
create policy "medical_drives_public_read"
  on public.medical_drives for select
  using (is_active = true and deleted_at is null);

-- Residents can read their own registrations.
create policy "drive_registrations_own_read"
  on public.drive_registrations for select
  using (auth.uid() = user_id);

-- Residents can cancel their own pending registration.
create policy "drive_registrations_own_cancel"
  on public.drive_registrations for update
  using (auth.uid() = user_id and status = 'pending')
  with check (status = 'cancelled');

-- ============================================================================
-- 5. RPC: register_for_drive
-- ============================================================================
-- Atomically: validates eligibility, locks the drive row, decrements
-- stock_remaining, generates a typed applicant number, computes a weighted
-- priority score, and inserts a drive_registrations row.
--
-- Priority scoring weights (AGENTS.md §3 — Weighted Eligibility Scoring):
--   PWD:              +30
--   Senior (≥60):     +20
--   Infant/Toddler(<5):+15
--   Comorbidity:       +5 each, capped at +20 total
--   Prior dose on file:+10
create or replace function public.register_for_drive(
  p_drive_id       uuid,
  p_age            integer,
  p_is_pwd         boolean,
  p_comorbidities  text[],
  p_prior_dose_date date default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id          uuid    := auth.uid();
  v_drive            public.medical_drives;
  v_prefix           text;
  v_applicant_number text;
  v_score            numeric := 0;
  v_reg              public.drive_registrations;
begin
  -- Auth guard
  if v_user_id is null then
    raise exception 'Not authenticated' using errcode = 'P0001';
  end if;

  -- Lock drive row so concurrent registrations can''t oversell
  select * into v_drive
  from public.medical_drives
  where id = p_drive_id
    and is_active   = true
    and deleted_at is null
  for update;

  if not found then
    raise exception 'Drive not found or inactive' using errcode = 'P0002';
  end if;

  if v_drive.stock_remaining <= 0 then
    raise exception 'No remaining slots for this drive' using errcode = 'P0003';
  end if;

  -- Duplicate-registration guard
  if exists(
    select 1 from public.drive_registrations
    where drive_id = p_drive_id and user_id = v_user_id
  ) then
    raise exception 'Already registered for this drive' using errcode = 'P0004';
  end if;

  -- Applicant-number prefix by drive type
  v_prefix := case v_drive.type
    when 'vaccination'    then 'VAC'
    when 'maternal_care'  then 'MAT'
    when 'blood_drive'    then 'BLD'
    when 'dental'         then 'DEN'
    when 'optical'        then 'OPT'
    when 'medicine'       then 'MED'
    when 'emergency_kit'  then 'EMK'
    when 'screening'      then 'SCR'
    when 'consultation'   then 'CON'
    when 'minor_surgical' then 'SRG'
    else                       'DRV'
  end;

  v_applicant_number :=
    v_prefix || '-' ||
    to_char(now(), 'YYYYMMDD') || '-' ||
    lpad((v_drive.stock_total - v_drive.stock_remaining + 1)::text, 4, '0');

  -- Weighted priority score
  if p_is_pwd                    then v_score := v_score + 30; end if;
  if p_age >= 60                 then v_score := v_score + 20; end if;
  if p_age < 5                   then v_score := v_score + 15; end if;
  v_score := v_score + least(
    coalesce(array_length(p_comorbidities, 1), 0) * 5, 20
  );
  if p_prior_dose_date is not null then v_score := v_score + 10; end if;

  -- Insert registration
  insert into public.drive_registrations (
    drive_id, user_id, applicant_number,
    age, is_pwd, comorbidities, prior_dose_date,
    priority_score, status
  ) values (
    p_drive_id, v_user_id, v_applicant_number,
    p_age, p_is_pwd,
    coalesce(p_comorbidities, '{}'), p_prior_dose_date,
    v_score, 'pending'
  )
  returning * into v_reg;

  -- Decrement available stock
  update public.medical_drives
  set stock_remaining = stock_remaining - 1
  where id = p_drive_id;

  return json_build_object(
    'registration_id',  v_reg.id,
    'applicant_number', v_applicant_number,
    'priority_score',   v_score,
    'status',           v_reg.status
  );
end;
$$;
